import type { DialectDefinition } from "./types";

/**
 * Curated dialect registry.
 *
 * No free translation API exposes dialects, so this table is the feature. Each
 * entry is hand written and reviewable, and a contributor adds a dialect by
 * appending one object here rather than by touching any code.
 *
 * Lexicon direction is always "what the base translation produced" to "what
 * this region actually says".
 */
export const DIALECTS: readonly DialectDefinition[] = [
  /* ------------------------------------------------------------ Spanish */
  {
    code: "es-ES",
    base: "es",
    name: "European Spanish",
    native: "Español de España",
    region: "Spain",
    providerLocale: "es-ES",
    ttsLocales: ["es-ES"],
    summary: "Peninsular vocabulary and the vosotros second person plural.",
    lexicon: [
      { from: "computadora", to: "ordenador", confidence: "high" },
      { from: "carro", to: "coche", confidence: "high" },
      { from: "celular", to: "móvil", confidence: "high" },
      { from: "jugo", to: "zumo", confidence: "high" },
      { from: "papa", to: "patata", confidence: "high" },
      { from: "lentes", to: "gafas", confidence: "high" },
      { from: "manejar", to: "conducir", confidence: "medium" },
    ],
  },
  {
    code: "es-MX",
    base: "es",
    name: "Mexican Spanish",
    native: "Español mexicano",
    region: "Mexico",
    providerLocale: "es-MX",
    ttsLocales: ["es-MX", "es-US"],
    summary: "The most widely spoken Spanish variety. Uses ustedes, never vosotros.",
    lexicon: [
      { from: "ordenador", to: "computadora", confidence: "high" },
      { from: "coche", to: "carro", confidence: "high" },
      { from: "auto", to: "carro", confidence: "medium", note: "auto is Rioplatense, Mexico says carro" },
      { from: "móvil", to: "celular", confidence: "high" },
      { from: "zumo", to: "jugo", confidence: "high" },
      { from: "patata", to: "papa", confidence: "high" },
      { from: "gafas", to: "lentes", confidence: "high" },
      { from: "piso", to: "departamento", confidence: "medium" },
      { from: "conducir", to: "manejar", confidence: "medium" },
      { from: "vosotros", to: "ustedes", confidence: "high", note: "vosotros is not used in the Americas" },
      { from: "coger", to: "tomar", confidence: "high", note: "coger is vulgar in Mexico" },
    ],
  },
  {
    code: "es-AR",
    base: "es",
    name: "Rioplatense Spanish",
    native: "Español rioplatense",
    region: "Argentina and Uruguay",
    providerLocale: "es-AR",
    ttsLocales: ["es-AR"],
    summary: "Voseo, distinct produce vocabulary and Italian influenced intonation.",
    lexicon: [
      { from: "ordenador", to: "computadora", confidence: "high" },
      { from: "coche", to: "auto", confidence: "high" },
      { from: "móvil", to: "celular", confidence: "high" },
      { from: "autobús", to: "colectivo", confidence: "high" },
      { from: "aguacate", to: "palta", confidence: "high" },
      { from: "fresa", to: "frutilla", confidence: "high" },
      { from: "plátano", to: "banana", confidence: "high" },
      { from: "tú", to: "vos", confidence: "medium", note: "voseo also changes the verb form, which this overlay does not conjugate" },
    ],
  },

  /* --------------------------------------------------------- Portuguese */
  {
    code: "pt-BR",
    base: "pt",
    name: "Brazilian Portuguese",
    native: "Português brasileiro",
    region: "Brazil",
    providerLocale: "pt-BR",
    ttsLocales: ["pt-BR"],
    summary: "The majority variety. Different everyday nouns and heavier gerund use.",
    lexicon: [
      { from: "comboio", to: "trem", confidence: "high" },
      { from: "autocarro", to: "ônibus", confidence: "high" },
      { from: "telemóvel", to: "celular", confidence: "high" },
      { from: "casa de banho", to: "banheiro", confidence: "high" },
      { from: "pequeno-almoço", to: "café da manhã", confidence: "high" },
      { from: "sumo", to: "suco", confidence: "high" },
      { from: "ecrã", to: "tela", confidence: "high" },
      { from: "rapariga", to: "garota", confidence: "high", note: "rapariga is offensive in Brazil" },
    ],
  },
  {
    code: "pt-PT",
    base: "pt",
    name: "European Portuguese",
    native: "Português europeu",
    region: "Portugal",
    providerLocale: "pt-PT",
    ttsLocales: ["pt-PT"],
    summary: "Peninsular vocabulary, closed vowels and mesoclitic pronouns.",
    lexicon: [
      { from: "trem", to: "comboio", confidence: "high" },
      { from: "ônibus", to: "autocarro", confidence: "high" },
      { from: "celular", to: "telemóvel", confidence: "high" },
      { from: "banheiro", to: "casa de banho", confidence: "high" },
      { from: "café da manhã", to: "pequeno-almoço", confidence: "high" },
      { from: "suco", to: "sumo", confidence: "high" },
      { from: "tela", to: "ecrã", confidence: "high" },
      { from: "time", to: "equipa", confidence: "high" },
    ],
  },

  /* ------------------------------------------------------------ English */
  {
    code: "en-US",
    base: "en",
    name: "American English",
    native: "American English",
    region: "United States",
    providerLocale: "en-US",
    ttsLocales: ["en-US"],
    summary: "Webster spelling and North American vocabulary.",
    orthography: [
      { pattern: "\\bcolour\\b", replace: "color" },
      { pattern: "\\bcentre\\b", replace: "center" },
      { pattern: "\\bfavourite\\b", replace: "favorite" },
      { pattern: "\\borganisation\\b", replace: "organization" },
      { pattern: "\\brealise\\b", replace: "realize" },
    ],
    lexicon: [
      { from: "lorry", to: "truck", confidence: "high" },
      { from: "lift", to: "elevator", confidence: "high" },
      { from: "biscuit", to: "cookie", confidence: "high" },
      { from: "petrol", to: "gasoline", confidence: "high" },
      { from: "autumn", to: "fall", confidence: "medium" },
      { from: "rubbish", to: "trash", confidence: "high" },
      { from: "jumper", to: "sweater", confidence: "high" },
      { from: "torch", to: "flashlight", confidence: "high" },
      { from: "pavement", to: "sidewalk", confidence: "high" },
      { from: "nappy", to: "diaper", confidence: "high" },
    ],
  },
  {
    code: "en-GB",
    base: "en",
    name: "British English",
    native: "British English",
    region: "United Kingdom",
    providerLocale: "en-GB",
    ttsLocales: ["en-GB"],
    summary: "Oxford spelling and British vocabulary.",
    orthography: [
      { pattern: "\\bcolor\\b", replace: "colour" },
      { pattern: "\\bcenter\\b", replace: "centre" },
      { pattern: "\\bfavorite\\b", replace: "favourite" },
      { pattern: "\\borganization\\b", replace: "organisation" },
    ],
    lexicon: [
      { from: "elevator", to: "lift", confidence: "high" },
      { from: "apartment", to: "flat", confidence: "medium" },
      { from: "gasoline", to: "petrol", confidence: "high" },
      { from: "sidewalk", to: "pavement", confidence: "high" },
      { from: "flashlight", to: "torch", confidence: "high" },
      { from: "french fries", to: "chips", confidence: "high" },
    ],
  },
  {
    code: "en-IN",
    base: "en",
    name: "Indian English",
    native: "Indian English",
    region: "India",
    providerLocale: "en-IN",
    ttsLocales: ["en-IN"],
    summary: "South Asian vocabulary, lakh and crore numerals, British spelling base.",
    lexicon: [
      { from: "eggplant", to: "brinjal", confidence: "medium" },
      { from: "bell pepper", to: "capsicum", confidence: "medium" },
      { from: "cilantro", to: "coriander", confidence: "high" },
      { from: "hundred thousand", to: "lakh", confidence: "medium" },
      { from: "ten million", to: "crore", confidence: "medium" },
    ],
  },
  {
    code: "en-PK",
    base: "en",
    name: "Pakistani English",
    native: "Pakistani English",
    region: "Pakistan",
    ttsLocales: ["en-IN", "en-GB"],
    summary: "British spelling base with South Asian vocabulary and Urdu loanwords.",
    lexicon: [
      { from: "hundred thousand", to: "lakh", confidence: "medium" },
      { from: "ten million", to: "crore", confidence: "medium" },
      { from: "eggplant", to: "brinjal", confidence: "medium" },
      { from: "traffic circle", to: "roundabout", confidence: "high" },
    ],
  },
  {
    code: "en-AU",
    base: "en",
    name: "Australian English",
    native: "Australian English",
    region: "Australia",
    providerLocale: "en-AU",
    ttsLocales: ["en-AU"],
    summary: "British spelling with a distinct colloquial register.",
    lexicon: [
      { from: "gasoline", to: "petrol", confidence: "high" },
      { from: "flip flops", to: "thongs", confidence: "medium" },
      { from: "afternoon", to: "arvo", confidence: "low", note: "informal register only" },
    ],
  },

  /* ------------------------------------------------------------- Arabic */
  {
    code: "ar-EG",
    base: "ar",
    name: "Egyptian Arabic",
    native: "اللهجة المصرية",
    region: "Egypt",
    dir: "rtl",
    ttsLocales: ["ar-EG", "ar-SA"],
    summary: "The most widely understood spoken Arabic, thanks to Egyptian cinema.",
    lexicon: [
      { from: "ماذا", to: "ايه", confidence: "high", note: "what" },
      { from: "كيف", to: "ازاي", confidence: "high", note: "how" },
      { from: "الآن", to: "دلوقتي", confidence: "high", note: "now" },
      { from: "جيد", to: "كويس", confidence: "high", note: "good" },
      { from: "ليس", to: "مش", confidence: "high", note: "not" },
      { from: "أريد", to: "عايز", confidence: "high", note: "I want" },
      { from: "لماذا", to: "ليه", confidence: "high", note: "why" },
    ],
  },
  {
    code: "ar-MA",
    base: "ar",
    name: "Moroccan Arabic",
    native: "الدارجة المغربية",
    region: "Morocco",
    dir: "rtl",
    ttsLocales: ["ar-MA", "ar-SA"],
    summary: "Darija, heavily influenced by Amazigh and French. Distant from Standard Arabic.",
    lexicon: [
      { from: "كيف", to: "كيفاش", confidence: "high", note: "how" },
      { from: "الآن", to: "دابا", confidence: "high", note: "now" },
      { from: "أريد", to: "بغيت", confidence: "high", note: "I want" },
      { from: "جيد", to: "مزيان", confidence: "high", note: "good" },
      { from: "ماذا", to: "شنو", confidence: "high", note: "what" },
    ],
  },
  {
    code: "ar-SA",
    base: "ar",
    name: "Gulf Arabic",
    native: "اللهجة الخليجية",
    region: "Arabian Peninsula",
    dir: "rtl",
    providerLocale: "ar-SA",
    ttsLocales: ["ar-SA"],
    summary: "Peninsular spoken Arabic, closest of the dialects to the written standard.",
    lexicon: [
      { from: "ماذا", to: "وش", confidence: "high", note: "what" },
      { from: "كيف", to: "كيف", confidence: "low" },
      { from: "الآن", to: "الحين", confidence: "high", note: "now" },
      { from: "أريد", to: "أبغى", confidence: "high", note: "I want" },
    ],
  },

  /* --------------------------------------------------------- South Asia */
  {
    code: "ur-PK",
    base: "ur",
    name: "Pakistani Urdu",
    native: "پاکستانی اردو",
    region: "Pakistan",
    script: "Arab",
    dir: "rtl",
    providerLocale: "ur-PK",
    ttsLocales: ["ur-PK", "ur-IN"],
    summary: "The national standard, with heavier Persian and Arabic vocabulary.",
    lexicon: [
      { from: "बिजली", to: "بجلی", confidence: "medium", note: "cross script leakage from Hindi sources" },
    ],
  },
  {
    code: "ur-Deva",
    base: "ur",
    name: "Urdu in Devanagari",
    native: "उर्दू",
    region: "India",
    script: "Deva",
    dir: "ltr",
    ttsLocales: ["hi-IN"],
    summary: "Urdu vocabulary written in Devanagari, as often seen in Indian publishing.",
    transliterate: "urdu-to-devanagari",
  },
  {
    code: "pa-Guru",
    base: "pa",
    name: "Punjabi in Gurmukhi",
    native: "ਪੰਜਾਬੀ",
    region: "Indian Punjab",
    script: "Guru",
    dir: "ltr",
    providerLocale: "pa",
    ttsLocales: ["pa-IN", "pa-Guru-IN"],
    summary: "Eastern Punjabi, written in Gurmukhi. The default form most tools assume.",
  },
  {
    code: "pa-Arab",
    base: "pa",
    name: "Punjabi in Shahmukhi",
    native: "پنجابی",
    region: "Pakistani Punjab",
    script: "Arab",
    dir: "rtl",
    ttsLocales: ["ur-PK"],
    summary: "Western Punjabi, written in Shahmukhi. The same language in a different script, and the form almost no translation tool supports.",
    transliterate: "gurmukhi-to-shahmukhi",
  },
  {
    code: "hi-Latn",
    base: "hi",
    name: "Hinglish",
    native: "Hinglish",
    region: "India, informal",
    script: "Latn",
    dir: "ltr",
    ttsLocales: ["hi-IN", "en-IN"],
    summary: "Hindi romanised into Latin script, the everyday register of Indian messaging.",
    transliterate: "devanagari-to-latin",
  },

  /* ------------------------------------------------------------ Chinese */
  {
    code: "zh-Hans",
    base: "zh",
    name: "Simplified Chinese",
    native: "简体中文",
    region: "Mainland China and Singapore",
    script: "Hans",
    providerLocale: "zh-CN",
    ttsLocales: ["zh-CN"],
    summary: "Simplified characters and mainland vocabulary.",
    lexicon: [
      { from: "軟體", to: "软件", confidence: "high", note: "software" },
      { from: "計程車", to: "出租车", confidence: "high", note: "taxi" },
      { from: "腳踏車", to: "自行车", confidence: "high", note: "bicycle" },
    ],
  },
  {
    code: "zh-Hant",
    base: "zh",
    name: "Traditional Chinese",
    native: "繁體中文",
    region: "Taiwan",
    script: "Hant",
    providerLocale: "zh-TW",
    ttsLocales: ["zh-TW"],
    summary: "Traditional characters and Taiwanese vocabulary.",
    lexicon: [
      { from: "软件", to: "軟體", confidence: "high", note: "software" },
      { from: "出租车", to: "計程車", confidence: "high", note: "taxi" },
      { from: "自行车", to: "腳踏車", confidence: "high", note: "bicycle" },
      { from: "信息", to: "資訊", confidence: "medium", note: "information" },
    ],
  },
  {
    code: "zh-Hant-HK",
    base: "zh",
    name: "Hong Kong Chinese",
    native: "香港繁體",
    region: "Hong Kong",
    script: "Hant",
    providerLocale: "zh-HK",
    ttsLocales: ["zh-HK", "yue-HK"],
    summary: "Traditional characters with Cantonese vocabulary and English loanwords.",
    lexicon: [
      { from: "出租车", to: "的士", confidence: "high", note: "taxi, from the English" },
      { from: "公共汽车", to: "巴士", confidence: "high", note: "bus, from the English" },
      { from: "草莓", to: "士多啤梨", confidence: "medium", note: "strawberry, from the English" },
    ],
  },

  /* ------------------------------------------------------------- Europe */
  {
    code: "fr-FR",
    base: "fr",
    name: "Metropolitan French",
    native: "Français de France",
    region: "France",
    providerLocale: "fr-FR",
    ttsLocales: ["fr-FR"],
    summary: "The reference standard for written French.",
    lexicon: [
      { from: "courriel", to: "e-mail", confidence: "medium" },
      { from: "fin de semaine", to: "week-end", confidence: "high" },
      { from: "magasiner", to: "faire du shopping", confidence: "high" },
    ],
  },
  {
    code: "fr-CA",
    base: "fr",
    name: "Quebec French",
    native: "Français québécois",
    region: "Quebec",
    providerLocale: "fr-CA",
    ttsLocales: ["fr-CA"],
    summary: "Distinct vocabulary and a strong preference for French coinages over English loans.",
    lexicon: [
      { from: "e-mail", to: "courriel", confidence: "high" },
      { from: "week-end", to: "fin de semaine", confidence: "high" },
      { from: "shopping", to: "magasinage", confidence: "high" },
      { from: "parking", to: "stationnement", confidence: "high" },
      { from: "déjeuner", to: "dîner", confidence: "low", note: "meal names shift by one: déjeuner is breakfast in Quebec" },
    ],
  },
  {
    code: "de-DE",
    base: "de",
    name: "German",
    native: "Bundesdeutsch",
    region: "Germany",
    providerLocale: "de-DE",
    ttsLocales: ["de-DE"],
    summary: "The federal German standard.",
  },
  {
    code: "de-AT",
    base: "de",
    name: "Austrian German",
    native: "Österreichisches Deutsch",
    region: "Austria",
    providerLocale: "de-AT",
    ttsLocales: ["de-AT"],
    summary: "Distinct food vocabulary and month names, officially recognised.",
    lexicon: [
      { from: "Kartoffel", to: "Erdapfel", confidence: "high" },
      { from: "Tomate", to: "Paradeiser", confidence: "high" },
      { from: "Sahne", to: "Obers", confidence: "high" },
      { from: "Januar", to: "Jänner", confidence: "high" },
      { from: "Tüte", to: "Sackerl", confidence: "high" },
      { from: "Brötchen", to: "Semmel", confidence: "high" },
    ],
  },
  {
    code: "de-CH",
    base: "de",
    name: "Swiss German",
    native: "Schweizer Hochdeutsch",
    region: "Switzerland",
    providerLocale: "de-CH",
    ttsLocales: ["de-CH"],
    summary: "Swiss standard German, which never uses the sharp s.",
    orthography: [
      { pattern: "ß", replace: "ss", note: "Switzerland abolished the sharp s" },
    ],
    lexicon: [
      { from: "Fahrrad", to: "Velo", confidence: "high" },
      { from: "Straßenbahn", to: "Tram", confidence: "high" },
      { from: "parken", to: "parkieren", confidence: "high" },
    ],
  },
  {
    code: "sr-Cyrl",
    base: "sr",
    name: "Serbian in Cyrillic",
    native: "Српски",
    region: "Serbia",
    script: "Cyrl",
    ttsLocales: ["sr-RS"],
    summary: "The official script. Serbian is fully digraphic, so this maps one to one with Latin.",
  },
  {
    code: "sr-Latn",
    base: "sr",
    name: "Serbian in Latin",
    native: "Srpski",
    region: "Serbia and the diaspora",
    script: "Latn",
    ttsLocales: ["sr-RS", "hr-HR"],
    summary: "The Latin script form, mechanically reversible with Cyrillic.",
    transliterate: "serbian-cyrl-to-latn",
  },
  {
    code: "nl-BE",
    base: "nl",
    name: "Flemish",
    native: "Vlaams",
    region: "Belgium",
    providerLocale: "nl-BE",
    ttsLocales: ["nl-BE"],
    summary: "Belgian Dutch, with French influenced vocabulary.",
    lexicon: [
      { from: "leuk", to: "plezant", confidence: "medium" },
      { from: "sinaasappel", to: "appelsien", confidence: "medium" },
    ],
  },

  /* -------------------------------------------------------- East Asia */
  {
    code: "ja-Kansai",
    base: "ja",
    name: "Kansai Japanese",
    native: "関西弁",
    region: "Osaka and Kyoto",
    ttsLocales: ["ja-JP"],
    summary: "The best known regional Japanese, with its own copula and negation.",
    lexicon: [
      { from: "ありがとう", to: "おおきに", confidence: "high", note: "thank you" },
      { from: "違う", to: "ちゃう", confidence: "high", note: "that is wrong" },
      { from: "とても", to: "めっちゃ", confidence: "high", note: "very" },
      { from: "だめ", to: "あかん", confidence: "high", note: "no good" },
      { from: "本当", to: "ほんま", confidence: "high", note: "really" },
    ],
  },
  {
    code: "ko-KR",
    base: "ko",
    name: "South Korean",
    native: "한국어",
    region: "South Korea",
    providerLocale: "ko-KR",
    ttsLocales: ["ko-KR"],
    summary: "The Seoul standard, with English loanwords retained.",
  },
] as const;
